### ISSUE TITLE
Analytics in a scalelite environment

### ISSUE THREAD

**Issue by margmz** [betagouv/bbb-analytics#10]
Is it possible to run the application in an environment with scalelite and multiple BigBlueButton servers? The Security Salt is different on every server.

**Comment by jdauphant** [comment]
@margmz  It's not yet possible, we may need it on our side but it's not planned.
How many different Security Salt do you have ? do you have servers dynamically ?

**Comment by margmz** [comment]
We have like 30 servers, they are not dynamically deployed. We are going to study the project in more depth, I will let you know if we can implement it.

**Comment by jdauphant** [comment]
:wave:  @margmz The feature has been implemented with #15 it's in the v1.1 release
